name: Java CI with Maven and JIB Container Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        chmod +x mvnw
        ./mvnw test-compile
    - name: Unit Testing
      run: ./mvnw test -Dgroups=unit
    - name: Integration Testing
      run: ./mvnw test -Dgroups=integration
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
           java-version: '21'
           distribution: 'temurin'

      - name: Set build tag
        if: github.event_name == 'push'
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Set build tag for pull request
        if: github.event_name == 'pull_request'
        run: echo "TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Build and publish JIB container
        run: |
          chmod +x mvnw
          ./mvnw install -DskipTests=true -Djib.allowInsecureRegistries -Djib.httpTimeout=1200000
          ./mvnw jib:build -X -Djib.serialize=true -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GHCR_TOKEN }} -Djib.to.image=ghcr.io/${{ github.repository }}:${{ env.TAG }} -Djib.allowInsecureRegistries -Djib.httpTimeout=1200000 -Djib.disableUpdateChecks=true
        env:
          TAG: ${{ env.TAG }}
