name: Java CI with Maven and JIB Container Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
           java-version: '21'
           distribution: 'temurin'

      - name: Get short commit hash
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build and publish JIB container
        run: mvn -B compile jib:build -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} -Djib.to.image=ghcr.io/${{ github.repository }}:${{ env.TAG }} -Djib.allowInsecureRegistries -Djib.httpTimeout=1200000 -Djib.disableUpdateChecks=true
        env:
          TAG: ${{ env.TAG }}
